# -*- encoding: utf-8 -*-

=begin
#Nutanix Prism APIs

#Manage Tasks, Category Associations and Submit Batch Operations.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "nutanix_prism/version"

Gem::Specification.new do |s|
  s.name        = "nutanix_prism"
  s.version     = NutanixPrism::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["ManageIQ Developers"]
  s.email       = [""]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Nutanix Prism API"
  s.description = "Ruby gem for Nutanix Prism APIs"
  s.license     = "Apache-2.0"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
