=begin
#Nutanix Prism APIs

#Manage Tasks, Category Associations and Submit Batch Operations.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NutanixPrism::DomainManagerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DomainManagerApi' do
  before do
    # run before each test
    @api_instance = NutanixPrism::DomainManagerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DomainManagerApi' do
    it 'should create an instance of DomainManagerApi' do
      expect(@api_instance).to be_instance_of(NutanixPrism::DomainManagerApi)
    end
  end

  # unit tests for create_backup_target
  # Create backup target 
  # Creates a cluster or object store as the backup target. For a given Prism Central, there can be up to 3 clusters as backup targets  and 1 object store as backup target. If any cluster or object store is not eligible for backup or  lacks appropriate permissions, the API request will fail.  For object store backup targets, specifying backup policy is mandatory along  with the location of the object store. 
  # @param domain_manager_ext_id A unique identifier for the domain manager. 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param prism_v40_management_backup_target 
  # @param [Hash] opts the optional parameters
  # @return [CreateBackupTarget202Response]
  describe 'create_backup_target test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_domain_manager
  # Deploy a Prism Central
  # Deploys a Prism Central using the provided details. Prism Central Size, Network Config are mandatory fields to deploy Prism Central. The response from this endpoint contains the URL in the task object location header that can be used to track the request status.
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param prism_v40_config_domain_manager Request body to deploy a Prism Central.
  # @param [Hash] opts the optional parameters
  # @return [CreateDomainManager202Response]
  describe 'create_domain_manager test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_restore_source
  # Create restore source 
  # Creates a restore source pointing to a cluster or object store to restore the domain manager. The created  restore source is intended to be deleted after use. If the restore source is not deleted using the deleteRestoreSource API, then it is auto-deleted after sometime. Also note that a restore  source will not contain a backup policy. It is only used to access the backup data at the location from where  the Prism Central may be restored. Credentials used to access the restore source are not validated at the time  of creation of the restore source. They are validated when the restore source is used to fetch data. 
  # @param prism_v40_management_restore_source 
  # @param [Hash] opts the optional parameters
  # @return [CreateRestoreSource201Response]
  describe 'create_restore_source test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_backup_target_by_id
  # Delete backup target 
  # Removes cluster/object store from the backup targets. This will stop the cluster/object store  from backing up Prism Central data. 
  # @param domain_manager_ext_id A unique identifier for the domain manager. 
  # @param ext_id A globally unique identifier of an instance that is suitable for external consumption. 
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param [Hash] opts the optional parameters
  # @return [DeleteBackupTargetById202Response]
  describe 'delete_backup_target_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_restore_source_by_id
  # Delete restore source 
  # Deletes a restore source on a cluster/object store. 
  # @param ext_id A globally unique identifier of an instance that is suitable for external consumption. 
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_restore_source_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_backup_target_by_id
  # Fetch backup target 
  # Retrieves the backup targets (cluster or object store) from a domain manager and returns the backup configuration and lastSyncTimestamp parameter to the user. 
  # @param ext_id A globally unique identifier of an instance that is suitable for external consumption. 
  # @param domain_manager_ext_id A unique identifier for the domain manager. 
  # @param [Hash] opts the optional parameters
  # @return [GetBackupTargetById200Response]
  describe 'get_backup_target_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_domain_manager_by_id
  # Get the requested domain manager (Prism Central) entity
  # Fetches the attributes associated with the domain manager (Prism Central) resource based on the provided external identifier. It includes attributes like config, network, node and other information such as size, environment and resource specifications.
  # @param ext_id The external identifier of the domain manager (Prism Central) resource.
  # @param [Hash] opts the optional parameters
  # @return [GetDomainManagerById200Response]
  describe 'get_domain_manager_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_restore_point_by_id
  # Get restore point details 
  # Retrieves detailed information about a specific recovery point and provides essential domain manager information stored in the backup, which is required for the restoration process. 
  # @param restore_source_ext_id A unique identifier obtained from the restore source API that corresponds to the details provided for the  restore source. 
  # @param restorable_domain_manager_ext_id A unique identifier for the domain manager. 
  # @param ext_id Restore point ID for the backup created in cluster/object store. 
  # @param [Hash] opts the optional parameters
  # @return [GetRestorePointById200Response]
  describe 'get_restore_point_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_restore_source_by_id
  # Fetch restore source 
  # Retrieves the restore source from the PE cache store and returns the restore source configuration and external identifier to the user. 
  # @param ext_id A globally unique identifier of an instance that is suitable for external consumption. 
  # @param [Hash] opts the optional parameters
  # @return [GetRestoreSourceById200Response]
  describe 'get_restore_source_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_backup_targets
  # List backup targets 
  # Lists backup targets (cluster or object store) configured for a given domain manager. 
  # @param domain_manager_ext_id A unique identifier for the domain manager. 
  # @param [Hash] opts the optional parameters
  # @return [ListBackupTargets200Response]
  describe 'list_backup_targets test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_domain_managers
  # List domain manager (Prism Central) configuration details
  # Returns a list of elements representing the domain manager (Prism Central) instance.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :select A URL query parameter that allows clients to request a specific set of properties for each entity or complex type. Expression specified with the $select must conform to the [OData V4.01](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html) URL conventions. If a $select expression consists of a single select item that is an asterisk (i.e., *), then all properties on the matching resource will be returned. - config - extId 
  # @return [ListDomainManagers200Response]
  describe 'list_domain_managers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_restorable_domain_managers
  # List restorable domain managers 
  # Lists all the domain managers backed up at the object store/cluster. 
  # @param restore_source_ext_id A unique identifier obtained from the restore source API that corresponds to the details provided for the  restore source. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A URL query parameter that specifies the page number of the result set. It must be a positive integer between 0 and the maximum number of pages that are available for that resource. Any number out of this range might lead to no results. 
  # @option opts [Integer] :limit A URL query parameter that specifies the total number of records returned in the result set.  Must be a positive integer between 1 and 100. Any number out of this range will lead to a validation error. If the limit is not provided, a default value of 50 records will be returned in the result set. 
  # @option opts [String] :filter A URL query parameter that allows clients to filter a collection of resources. The expression specified with $filter is evaluated for each resource in the collection, and only items where the expression evaluates to true are included in the response. Expression specified with the $filter must conform to the [OData V4.01](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html) URL conventions. For example, filter &#39;$filter&#x3D;name eq &#39;karbon-ntnx-1.0&#39; would filter the result on cluster name &#39;karbon-ntnx1.0&#39;, filter &#39;$filter&#x3D;startswith(name, &#39;C&#39;)&#39; would filter on cluster name starting with &#39;C&#39;. The filter can be applied to the following fields: - extId 
  # @return [ListRestorableDomainManagers200Response]
  describe 'list_restorable_domain_managers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_restore_points
  # List restore points 
  # The list restore points API allows you to retrieve a list of available restore points,  which are snapshots of the domain manager taken at different times. These restore points can be used to revert the domain manager to a previous state. The list response includes the creation time and identifier ID for the configuration data.&lt;br&gt;  1. For cluster-based backups, only the most recent restore point is available, as backups are continuous.&lt;br&gt; 2. For object store-based backups, multiple restore points may be available, depending on the configured  Recovery Point Objective (RPO) and the retention period set on the s3 bucket. 
  # @param restore_source_ext_id A unique identifier obtained from the restore source API that corresponds to the details provided for the  restore source. 
  # @param restorable_domain_manager_ext_id A unique identifier for the domain manager. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A URL query parameter that specifies the page number of the result set. It must be a positive integer between 0 and the maximum number of pages that are available for that resource. Any number out of this range might lead to no results. 
  # @option opts [Integer] :limit A URL query parameter that specifies the total number of records returned in the result set.  Must be a positive integer between 1 and 100. Any number out of this range will lead to a validation error. If the limit is not provided, a default value of 50 records will be returned in the result set. 
  # @option opts [String] :filter A URL query parameter that allows clients to filter a collection of resources. The expression specified with $filter is evaluated for each resource in the collection, and only items where the expression evaluates to true are included in the response. Expression specified with the $filter must conform to the [OData V4.01](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html) URL conventions. For example, filter &#39;$filter&#x3D;name eq &#39;karbon-ntnx-1.0&#39; would filter the result on cluster name &#39;karbon-ntnx1.0&#39;, filter &#39;$filter&#x3D;startswith(name, &#39;C&#39;)&#39; would filter on cluster name starting with &#39;C&#39;. The filter can be applied to the following fields: - creationTime 
  # @option opts [String] :orderby A URL query parameter that allows clients to specify the sort criteria for the returned list of objects. Resources can be sorted in ascending order using asc or descending order using desc. If asc or desc are not specified, the resources will be sorted in ascending order by default. For example, &#39;$orderby&#x3D;templateName desc&#39; would get all templates sorted by templateName in descending order. The orderby can be applied to the following fields: - creationTime 
  # @option opts [String] :select A URL query parameter that allows clients to request a specific set of properties for each entity or complex type. Expression specified with the $select must conform to the [OData V4.01](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html) URL conventions. If a $select expression consists of a single select item that is an asterisk (i.e., *), then all properties on the matching resource will be returned. - creationTime - domainManager - extId - links - tenantId 
  # @return [ListRestorePoints200Response]
  describe 'list_restore_points test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for register
  # Register a domain manager (Prism Central) to a cluster
  # Registers a domain manager (Prism Central) instance to other entities like PE and PC. This process is asynchronous, creating a registration task and returning its UUID.
  # @param ext_id The external identifier of the domain manager (Prism Central) resource.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param prism_v40_management_cluster_registration_spec The registration request consists of the remote cluster details. Credentials must be of domain manager (Prism Central) role.
  # @param [Hash] opts the optional parameters
  # @return [Register202Response]
  describe 'register test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for restore
  # Restore domain manager 
  # The restore domain manager is a task-driven operation to restore a domain manager from a cluster or object store  backup location based on the selected restore point. 
  # @param restore_source_ext_id A unique identifier obtained from the restore source API that corresponds to the details provided for the  restore source. 
  # @param restorable_domain_manager_ext_id A unique identifier for the domain manager. 
  # @param ext_id Restore point ID for the backup created in cluster/object store. 
  # @param prism_v40_management_restore_spec 
  # @param [Hash] opts the optional parameters
  # @return [Restore202Response]
  describe 'restore test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unregister
  # Unregister a registered remote cluster from the local cluster
  # Unregister a registered remote cluster from the local cluster. This process is asynchronous, creating an unregisteration task and returning its UUID.
  # @param ext_id The external identifier of the domain manager (Prism Central) resource.
  # @param if_match The If-Match request header makes the request conditional. When not provided the server will respond with an HTTP 428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP 412 (Precondition Failed) response 
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param body Payload for unregistering a cluster
  # @param [Hash] opts the optional parameters
  # @return [Unregister202Response]
  describe 'unregister test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_backup_target_by_id
  # Update backup target 
  # Updates the credentials and/or RPO of the given object store. 
  # @param domain_manager_ext_id A unique identifier for the domain manager. 
  # @param ext_id A globally unique identifier of an instance that is suitable for external consumption. 
  # @param if_match The If-Match request header makes the request conditional. When not provided, the server will respond with  an HTTP-428 (Precondition Required) response code indicating that the server requires the request to be conditional. The server will allow the successful completion of PUT and PATCH operations, if the resource matches the ETag value returned to the response of a GET operation. If the conditional does not match, then an HTTP-412 (Precondition Failed) response will be returned.
  # @param ntnx_request_id A unique identifier that is associated with each request. The provided value must be opaque and preferably in Universal Unique Identifier (UUID) format. This identifier is also used as an idempotence token for safely retrying requests in case of network errors. All the supported Nutanix API clients add this auto-generated request identifier to each request. 
  # @param prism_v40_management_backup_target 
  # @param [Hash] opts the optional parameters
  # @return [UpdateBackupTargetById202Response]
  describe 'update_backup_target_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
