=begin
#Nutanix Prism APIs

#Manage Tasks, Category Associations and Submit Batch Operations.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixPrism::ClustermgmtV40ConfigClusterConfig
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixPrism::ClustermgmtV40ConfigClusterConfig do
  let(:instance) { NutanixPrism::ClustermgmtV40ConfigClusterConfig.new }

  describe 'test an instance of ClustermgmtV40ConfigClusterConfig' do
    it 'should create an instance of ClustermgmtV40ConfigClusterConfig' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixPrism::ClustermgmtV40ConfigClusterConfig)
    end
  end

  describe 'test attribute "should_enable_lockdown_mode"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "build_info"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
