=begin
#Nutanix Prism APIs

#Manage Tasks, Category Associations and Submit Batch Operations.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixPrism::CommonV10ConfigBasicAuth
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixPrism::CommonV10ConfigBasicAuth do
  let(:instance) { NutanixPrism::CommonV10ConfigBasicAuth.new }

  describe 'test an instance of CommonV10ConfigBasicAuth' do
    it 'should create an instance of CommonV10ConfigBasicAuth' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixPrism::CommonV10ConfigBasicAuth)
    end
  end

  describe 'test attribute "username"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "password"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
