=begin
#Nutanix Prism APIs

#Manage Tasks, Category Associations and Submit Batch Operations.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixPrism::PrismV40ConfigExternalNetwork
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixPrism::PrismV40ConfigExternalNetwork do
  let(:instance) { NutanixPrism::PrismV40ConfigExternalNetwork.new }

  describe 'test an instance of PrismV40ConfigExternalNetwork' do
    it 'should create an instance of PrismV40ConfigExternalNetwork' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixPrism::PrismV40ConfigExternalNetwork)
    end
  end

  describe 'test attribute "default_gateway"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "subnet_mask"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "ip_ranges"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "network_ext_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
