=begin
#Nutanix Prism APIs

#Manage Tasks, Category Associations and Submit Batch Operations.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixPrism::PrismV40ProtectpcPcvmRestoreFile
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixPrism::PrismV40ProtectpcPcvmRestoreFile do
  let(:instance) { NutanixPrism::PrismV40ProtectpcPcvmRestoreFile.new }

  describe 'test an instance of PrismV40ProtectpcPcvmRestoreFile' do
    it 'should create an instance of PrismV40ProtectpcPcvmRestoreFile' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixPrism::PrismV40ProtectpcPcvmRestoreFile)
    end
  end

  describe 'test attribute "file_path"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "file_content"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "is_encrypted"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "key_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "encryption_version"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
