=begin
#Nutanix Prism APIs

#Manage Tasks, Category Associations and Submit Batch Operations.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixPrism::PrismV40ManagementBackupTargetAllOfLocation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixPrism::PrismV40ManagementBackupTargetAllOfLocation do
  let(:instance) { NutanixPrism::PrismV40ManagementBackupTargetAllOfLocation.new }

  describe 'test an instance of PrismV40ManagementBackupTargetAllOfLocation' do
    it 'should create an instance of PrismV40ManagementBackupTargetAllOfLocation' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixPrism::PrismV40ManagementBackupTargetAllOfLocation)
    end
  end

  describe 'test attribute "object_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
