=begin
#Nutanix Prism APIs

#Manage Tasks, Category Associations and Submit Batch Operations.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixPrism::PrismV40ProtectpcPcEndpointFlavour
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixPrism::PrismV40ProtectpcPcEndpointFlavour do
  let(:instance) { NutanixPrism::PrismV40ProtectpcPcEndpointFlavour.new }

  describe 'test an instance of PrismV40ProtectpcPcEndpointFlavour' do
    it 'should create an instance of PrismV40ProtectpcPcEndpointFlavour' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixPrism::PrismV40ProtectpcPcEndpointFlavour)
    end
  end

end
