=begin
#Nutanix Prism APIs

#Manage Tasks, Category Associations and Submit Batch Operations.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NutanixPrism::VmmV40AhvConfigCloudInit
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NutanixPrism::VmmV40AhvConfigCloudInit do
  let(:instance) { NutanixPrism::VmmV40AhvConfigCloudInit.new }

  describe 'test an instance of VmmV40AhvConfigCloudInit' do
    it 'should create an instance of VmmV40AhvConfigCloudInit' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NutanixPrism::VmmV40AhvConfigCloudInit)
    end
  end

  describe 'test attribute "datasource_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "metadata"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cloud_init_script"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
