=begin
#Nutanix Prism APIs

#Manage Tasks, Category Associations and Submit Batch Operations.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module NutanixPrism
  class PrismV40ProtectpcPcEndpointFlavour
    K_S3 = "kS3".freeze
    UNKNOWN = "$UNKNOWN".freeze

    def self.all_vars
      @all_vars ||= [K_S3, UNKNOWN].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PrismV40ProtectpcPcEndpointFlavour.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PrismV40ProtectpcPcEndpointFlavour"
    end
  end
end
