=begin
#Nutanix Prism APIs

#Manage Tasks, Category Associations and Submit Batch Operations.

The version of the OpenAPI document: 4.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module NutanixPrism
  class PrismV40ConfigResourceType
    VM = "VM".freeze
    MH_VM = "MH_VM".freeze
    IMAGE = "IMAGE".freeze
    SUBNET = "SUBNET".freeze
    CLUSTER = "CLUSTER".freeze
    HOST = "HOST".freeze
    REPORT = "REPORT".freeze
    MARKETPLACE_ITEM = "MARKETPLACE_ITEM".freeze
    BLUEPRINT = "BLUEPRINT".freeze
    APP = "APP".freeze
    VOLUMEGROUP = "VOLUMEGROUP".freeze
    IMAGE_PLACEMENT_POLICY = "IMAGE_PLACEMENT_POLICY".freeze
    NETWORK_SECURITY_POLICY = "NETWORK_SECURITY_POLICY".freeze
    NETWORK_SECURITY_RULE = "NETWORK_SECURITY_RULE".freeze
    VM_HOST_AFFINITY_POLICY = "VM_HOST_AFFINITY_POLICY".freeze
    VM_VM_ANTI_AFFINITY_POLICY = "VM_VM_ANTI_AFFINITY_POLICY".freeze
    QOS_POLICY = "QOS_POLICY".freeze
    NGT_POLICY = "NGT_POLICY".freeze
    PROTECTION_RULE = "PROTECTION_RULE".freeze
    ACCESS_CONTROL_POLICY = "ACCESS_CONTROL_POLICY".freeze
    STORAGE_POLICY = "STORAGE_POLICY".freeze
    IMAGE_RATE_LIMIT = "IMAGE_RATE_LIMIT".freeze
    RECOVERY_PLAN = "RECOVERY_PLAN".freeze
    BUNDLE = "BUNDLE".freeze
    POLICY_SCHEMA = "POLICY_SCHEMA".freeze
    HOST_NIC = "HOST_NIC".freeze
    ACTION_RULE = "ACTION_RULE".freeze
    UNKNOWN = "$UNKNOWN".freeze
    REDACTED = "$REDACTED".freeze

    def self.all_vars
      @all_vars ||= [VM, MH_VM, IMAGE, SUBNET, CLUSTER, HOST, REPORT, MARKETPLACE_ITEM, BLUEPRINT, APP, VOLUMEGROUP, IMAGE_PLACEMENT_POLICY, NETWORK_SECURITY_POLICY, NETWORK_SECURITY_RULE, VM_HOST_AFFINITY_POLICY, VM_VM_ANTI_AFFINITY_POLICY, QOS_POLICY, NGT_POLICY, PROTECTION_RULE, ACCESS_CONTROL_POLICY, STORAGE_POLICY, IMAGE_RATE_LIMIT, RECOVERY_PLAN, BUNDLE, POLICY_SCHEMA, HOST_NIC, ACTION_RULE, UNKNOWN, REDACTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PrismV40ConfigResourceType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PrismV40ConfigResourceType"
    end
  end
end
